version: '3.8'

services:
  database:
    image: mongo
    restart: always
    env_file:
      - docker.env
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./scripts/mongo:/docker-entrypoint-initdb.d/
      - ./mongo:/data/db